<a href="https://colab.research.google.com/github/LeonZou7/PyStudy-Log/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

print(np.__version__)
print(torch.__version__)

1.18.3
1.5.0+cu101


In [14]:
a = np.ones((2, 2))
b = np.zeros((3, 3))
c = np.eye(4)   # 单位数组
print("a: ",a)
print("b: ", b)
print("c: ", c)

a:  [[1. 1.]
 [1. 1.]]
b:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
c:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# 一维等差数组
a = np.arange(1, 9)

# 二维等差数组
b = np.arange(6).reshape(2, 3)

# 等距一维数组
c = np.linspace(1, 10, num=4)

print("a: ", a)
print("b: ", b)
print("c: ", c)

a:  [1 2 3 4 5 6 7 8]
b:  [[0 1 2]
 [3 4 5]]
c:  [ 1.  4.  7. 10.]


In [19]:
# 二维随机数组
a = np.random.rand(2, 3)

# 小于5的二维随机整数数组
b = np.random.randint(5, size=(2, 3))

print("a: ", a)
print("b: ", b)

a:  [[0.0814259  0.67256893 0.05919832]
 [0.37484968 0.92034775 0.33175629]]
b:  [[4 1 0]
 [1 0 2]]


In [26]:
# 数组运算
a = np.array([1, 2, 3, 4])
b = np.random.randint(10, size=(1, 4))

print(a, b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[1 2 3 4] [[8 5 7 6]]
[[ 9  7 10 10]]
[[-7 -3 -4 -2]]
[[ 8 10 21 24]]
[[0.125      0.4        0.42857143 0.66666667]]


In [30]:
# 矩阵运算
a = np.array([[1, 2],
        [3, 4]])
b = np.array([[5, 6],
        [7, 8]])

print(a + b)
print(a - b)
print(a * b)    # 元素间乘法
print(np.dot(a, b)) # 矩阵乘法
print(2 * a)    # 数乘
print(a.T)  # 转置矩阵
print(np.linalg.inv(a)) # 逆矩阵

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[2 4]
 [6 8]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
a = np.random.randint(6, size=(1,3))
np.sin(a)   # 三角函数
np.exp(a)   # e为底的指数函数
np.sqrt(a)  # 平方根
np.abs(a)   # 绝对值
np.power(a, 2)  # 指数运算

array([[4, 4, 1]])

In [12]:
# 二维数组切片和索引
a = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

print(a[1:3])
print(a[:-1])
print(a[:, 1])  # 取第2列
print(a[1, :])  # 取第2行

[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[2 5 8]
[4 5 6]


In [32]:
# 数组形状操作
a = np.random.random((2, 3))

print(a.shape)
print(a.reshape(3, 2))  # 不改变原始数组
print(a.resize(3, 2))   # 改变原始数组
print(a.ravel())  # 展平数组
print('-------')

b = np.random.randint(10, size=(3, 3))
c = np.random.randint(10, size=(3, 3))

print(b)
print(c)
print('-------')
print(np.vstack((b, c)))  # 垂直拼合数组
print(np.hstack((b, c)))  # 水平拼合数组
print('-------')
print(np.vsplit(b, 3))  # 沿纵轴分割数组
print(np.hsplit(c, 3))  # 沿横轴分割数组

(2, 3)
[[4.20810637e-02 4.69219044e-01]
 [1.07183696e-01 4.02592000e-04]
 [6.83220969e-01 4.85040835e-01]]
None
[4.20810637e-02 4.69219044e-01 1.07183696e-01 4.02592000e-04
 6.83220969e-01 4.85040835e-01]
-------
[[6 4 8]
 [5 7 0]
 [8 9 2]]
[[0 8 1]
 [9 7 0]
 [3 9 2]]
-------
[[6 4 8]
 [5 7 0]
 [8 9 2]
 [0 8 1]
 [9 7 0]
 [3 9 2]]
[[6 4 8 0 8 1]
 [5 7 0 9 7 0]
 [8 9 2 3 9 2]]
-------
[array([[6, 4, 8]]), array([[5, 7, 0]]), array([[8, 9, 2]])]
[array([[0],
       [9],
       [3]]), array([[8],
       [7],
       [9]]), array([[1],
       [0],
       [2]])]


In [44]:
# 数组排序
a = np.random.randint(10, size=(3, 3))
print(a)
print('-------')
print(np.max(a, axis=0))    # 每列最大值
print(np.min(a, axis=1))    # 每行最小值
print('-------')
print(np.argmax(a, axis=0)) # 每列最大值索引
print(np.argmin(b, axis=1)) # 每行最小值索引

[[8 3 7]
 [8 6 4]
 [2 4 7]]
-------
[8 6 7]
[3 4 2]
-------
[0 1 0]
[1 2 2]


In [45]:
# 数组统计
a = np.random.randint(10, size=(3, 3))

print(a)
print('-------')
print(np.median(a, axis=0)) # 每列中位数
print(np.mean(a, axis=1)) # 每行算术平均值
print('-------')
print(np.average(a, axis=0))    # 每列加权平均值
print(np.var(a, axis=1))    # 每行方差
print(np.std(a, axis=0))    # 每列标准差

[[9 8 8]
 [0 8 8]
 [2 8 0]]
-------
[2. 8. 8.]
[8.33333333 5.33333333 3.33333333]
-------
[3.66666667 8.         5.33333333]
[ 0.22222222 14.22222222 11.55555556]
[3.8586123  0.         3.77123617]


In [46]:
# 创建一个 0-10 的一维数组，并将 (1, 9] 之间的数全部反转成负数
Z = np.arange(11)
Z[(1 < Z) & (Z <= 9)] *= -1
Z

array([ 0,  1, -2, -3, -4, -5, -6, -7, -8, -9, 10])

In [47]:
# 找出两个一维数组中相同的元素
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print("Z1:", Z1)
print("Z2:", Z2)
np.intersect1d(Z1, Z2)

Z1: [0 9 5 2 2 3 8 3 1 0]
Z2: [4 6 7 3 8 3 0 6 7 1]


array([0, 1, 3, 8])

In [48]:
# 不同方法提取一个随机数组的整数部分
Z = np.random.uniform(0, 10, 10)
print("原始值: ", Z)

print("方法 1: ", Z - Z % 1)
print("方法 2: ", np.floor(Z))
print("方法 3: ", np.ceil(Z)-1)
print("方法 4: ", Z.astype(int))
print("方法 5: ", np.trunc(Z))

原始值:  [2.31782681 9.24435627 9.44716953 8.66540252 8.66708575 6.89673315
 5.74769827 2.93667823 8.34290259 7.04235737]
方法 1:  [2. 9. 9. 8. 8. 6. 5. 2. 8. 7.]
方法 2:  [2. 9. 9. 8. 8. 6. 5. 2. 8. 7.]
方法 3:  [2. 9. 9. 8. 8. 6. 5. 2. 8. 7.]
方法 4:  [2 9 9 8 8 6 5 2 8 7]
方法 5:  [2. 9. 9. 8. 8. 6. 5. 2. 8. 7.]


In [49]:
#  将二维数组的前两行进行顺序交换
A = np.arange(25).reshape(5, 5)
print(A)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [50]:
# 找出给定一维数组中非 0 元素的位置索引
Z = np.nonzero([1, 0, 2, 0, 1, 0, 4, 0])
Z

(array([0, 2, 4, 6]),)

In [51]:
# 对于二维随机数组中各元素，保留其 2 位小数
Z = np.random.random((5, 5))
print(Z)

np.set_printoptions(precision=2)
Z

[[0.59204052 0.74380552 0.18240923 0.58224648 0.65608683]
 [0.48360224 0.05815565 0.99825605 0.02436148 0.88259058]
 [0.58909763 0.6223073  0.20417286 0.36216227 0.2539131 ]
 [0.97005343 0.12648269 0.07766655 0.52066986 0.88684419]
 [0.82607178 0.79095118 0.52982949 0.93824204 0.6777357 ]]


array([[0.59, 0.74, 0.18, 0.58, 0.66],
       [0.48, 0.06, 1.  , 0.02, 0.88],
       [0.59, 0.62, 0.2 , 0.36, 0.25],
       [0.97, 0.13, 0.08, 0.52, 0.89],
       [0.83, 0.79, 0.53, 0.94, 0.68]])

In [52]:
# 将数组中各元素按指定分类转换为文本值
# 指定类别如下
# 1 → 汽车
# 2 → 公交车
# 3 → 火车

Z = np.random.randint(1, 4, 10)
print(Z)

label_map = {1: "汽车", 2: "公交车", 3: "火车"}

[label_map[x] for x in Z]

[1 1 2 2 3 2 3 1 1 3]


['汽车', '汽车', '公交车', '公交车', '火车', '公交车', '火车', '汽车', '汽车', '火车']

In [53]:
# 得到二维随机数组各行的最大值
Z = np.random.randint(1, 100, [5, 5])
print(Z)

np.amax(Z, axis=1)  # amin同理

[[57 84 81 37 40]
 [71 59 35 48 72]
 [54 28 54 41 86]
 [66 41 92 43 82]
 [89 98 34 20 54]]


array([84, 72, 86, 92, 98])

In [54]:
# 将 Ndarray 相邻元素依次累加
Z = np.random.randint(1, 10, 10)
print(Z)

"""
[第一个元素, 第一个元素 + 第二个元素, 第一个元素 + 第二个元素 + 第三个元素, ...]
"""
np.cumsum(Z)

[8 4 3 8 7 4 5 1 9 6]


array([ 8, 12, 15, 23, 30, 34, 39, 40, 49, 55])

In [55]:
# 按列连接两个数组
M1 = np.array([1, 2, 3])
M2 = np.array([4, 5, 6])

np.c_[M1, M2]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
# 按行连接两个数组
M1 = np.array([1, 2, 3])
M2 = np.array([4, 5, 6])

np.r_[M1, M2]

array([1, 2, 3, 4, 5, 6])